language: node_js
env:
  - NODE_VERSION="0.6"
  - NODE_VERSION="0.8"
  - NODE_VERSION="0.10.25"
  - NODE_VERSION="0.10.26"
  - NODE_VERSION="0.10.27"
  - NODE_VERSION="0.10.28"
  - NODE_VERSION="0.11.13"
node_js:
  - "0.10"
notifications:
  email:
    - rod@vagg.org
before_install:
  - rm -rf ~/.nvm
  - curl https://raw.github.com/creationix/nvm/master/install.sh | sh
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - cd test
  - npm install
script: npm test
