os:
  - linux
  - osx
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
notifications:
  email:
    - rod@vagg.org
install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then git clone https://github.com/creationix/nvm.git ~/.nvm && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION; fi
  - npm install npm
  - mv node_modules npm
  - npm/.bin/npm --version
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm/.bin/npm install
  - if [[ $TRAVIS_NODE_VERSION == "0.8" ]]; then node_modules/.bin/node-gyp rebuild --directory test; else node_modules/.bin/pangyp rebuild --directory test; fi
script: if [[ $TRAVIS_OS_NAME == "linux" ]]; then tap --gc test/js/*-test.js; else node_modules/.bin/tap --gc teset/js/*-test.js; fi
